config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show] do
    get 'activate', on: :member
  end
  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    resources :albums, on: :member, only: [:new]
  end

  resources :albums, except: [:new] do
    resources :tracks, on: :member, only: [:new]
  end

  resources :tracks,  except: [:new] do
    resources :notes, on: :member, only: [:new, :create]
  end

  resources :notes, only: [:destroy, :update, :edit]
end

app/models/note.rb
class Note < ActiveRecord::Base
  validates :body, :user_id, :track_id, presence: true
  belongs_to :user
  belongs_to :track
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_track, except: [:destroy]

  def new
    @note.new
  end

  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    @note.track_id = @track.id

    if @note.save
      redirect_to @track
    else
      flash.now[:errors] = @note.errors.full_messages
      redirect_to @track
    end
  end

  def destroy
    @note = Note.find(params[:id])
    track = @note.track

    if current_user.id == @note.user_id
      @note.destroy
      redirect_to track
    else
      render text: "You can not delete other users' notes!", status: :forbidden
    end
  end

  private

  def note_params
    params.require(:note).permit(:body)
  end

  def find_track
    @track = Track.find(params[:track_id])
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<h4>Add a new note: </h4>
<%= form_helper(track_notes_url(track), "POST") %>
  <textarea name="note[body]" rows="8" cols="80"></textarea>
  <input type="hidden" name="note[track_id]" value="<%= @track_id %>">
  <br>
  <input type="Submit" value="Add Note">
</form>

app/views/notes/_note.html.erb
<li>Posted by <%= note.user.email %>
  (<%= nice_time(note.created_at) %>): <%= note.body %>

  <% if note.user_id == current_user.id %>
    <%= button_to("Delete", note_url(note), method: :delete) %>
  <% end %>
</li>