config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show] do
    get 'activate', on: :member
  end
  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    resources :albums, on: :member, only: [:new]
  end

  resources :albums, except: [:new] do
    resources :tracks, on: :member, only: [:new]
  end

  resources :tracks,  except: [:new] do
    resources :notes, on: :member, only: [:new, :create]
  end

  resources :notes, only: [:destroy, :update, :edit]
end

app/models/track.rb
class Track < ActiveRecord::Base
  validates :album_id, :title, :track_type, presence: true
  validates :track_type, inclusion: %w(regular bonus)

  belongs_to :album
  has_many :notes

  has_one :band,
    through: :album,
    source: :band
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :find_track, only: [:edit, :show, :destroy, :update]
  before_action :require_current_user!

  def new
    @album = Album.find(params[:album_id])
    @albums = @album.band.albums
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to @track
    else
      flash.now[:errors] = @track.errors.full_messages
      @album = @track.album
      @albums = @album.band.albums
      render :new
    end
  end

  def destroy
    album = @track.album
    if @track.destroy
      redirect_to album
    else
      flash.now[:errors] = ["Track is invincible"]
      render @track
    end
  end

  def edit
    @album = @track.album
    @albums = @track.band.albums
  end

  def update
    if @track.update(track_params)
      redirect_to @track
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def show
  end

  def index
    @tracks = Track.all
  end

  private

  def track_params
    params.require(:track).permit(:title, :track_type, :album_id, :lyrics)
  end

  def find_track
    @track = Track.find(params[:id])
  end

end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_form.html.erb
<%= form_helper(action, method) %>
  <label>Album: </label>
  <select name="track[album_id]">
    <% albums.each do |a|%>
    <option value="<%= a.id %>"
            <%= "Selected" if a == album %>>
      <%= a.title %>
    </option>
    <% end %>
  </select>
  <br>
  <label>Track type: </label>
  <input type="radio"
         name="track[track_type]"
         value="regular" <%= "checked" if track.try(:track_type) == "regular" %>>
         Regular
  <input type="radio"
         name="track[track_type]"
         value="bonus"<%= "checked" if track.try(:track_type) == "bonus" %>>
         Bonus
  <br>
  <br>
  <label>Title: <input type="text" name="track[title]" value="<%= track.try(:title) %> "></label>
  <br>
  <label>Lryics: <textarea name="track[lyrics]" rows="8" cols="80"><%= @track.try(:lyrics) %></textarea></label>
  <br>
  <input type="submit" value="<%= button_text %>">
</label>

app/views/tracks/_track.html.erb
<li><%= link_to(track.title, track_url(track)) %></li>

app/views/tracks/edit.html.erb
<h1>Edit track</h1>
<%= render 'form', track: @track,
                   album: @track.album,
                   albums: @albums,
                   button_text: "Submit Changes",
                   action: track_url(@track), method: 'PATCH' %>
<br>
<%= link_to("<< Back to track", track_url(@track)) %>

app/views/tracks/index.html.erb
<h1>All Tracks</h1>
<ul>
  <%= render @tracks %>
</ul>

<br>
<%= link_to("<< Back to Albums", albums_url) %>

app/views/tracks/new.html.erb
<h1>Create a new track</h1>
<%= render 'form', track: @track,
                   album: @album,
                   albums: @albums,
                   button_text: "Create Track",
                   action: tracks_url,
                   method: 'POST' %>
<br>
<%= link_to("<< Back to album", album_url(@album)) %>

app/views/tracks/show.html.erb
<h1><%= @track.title %></h1>

<ul>
  <li>Artist: <%= @track.band.name %> </li>
  <li>Album: <%=@track.album.title  %></li>
  <li>Track type: <%=@track.track_type  %></li>
  <li>Lyrics: <%= ugly_lryics(@track.lyrics)  %></li>
</ul>

<% if @track.notes.length > 0 %>
  <h4>Notes: </h4>
  <ul>
    <%= render(@track.notes) %>
  </ul>
<% end %>


<%= render 'notes/form', track: @track%>

<br>
<%= button_to("Edit Track", edit_track_url(@track), method: :get) %>
<br>
<%= button_to("Delete Track", track_url(@track), method: :delete) %>
<br>
<%= link_to("<< Back to album", album_url(@track.album)) %>