config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show] do
    get 'activate', on: :member
  end
  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    resources :albums, on: :member, only: [:new]
  end

  resources :albums, except: [:new] do
    resources :tracks, on: :member, only: [:new]
  end

  resources :tracks,  except: [:new] do
    resources :notes, on: :member, only: [:new, :create]
  end

  resources :notes, only: [:destroy, :update, :edit]
end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :band_id, :title, :album_type, presence: true
  validates :album_type, inclusion: %w(studio live)

  belongs_to :band
  has_many :tracks, dependent: :destroy

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :find_album, only: [:edit, :show, :destroy, :update]
  before_action :find_bands, only: [:new, :edit]
  before_action :require_current_user!

  def new
    @band = Band.find(params[:band_id])
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to @album
    else
      flash.now[:errors] = @album.errors.full_messages
      @bands = Band.all
      @band = @album.band
      render :new
    end
  end

  def destroy
    band = @album.band
    if @album.destroy
      redirect_to band
    else
      flash.now[:errors] = ["Album is invincible"]
      render @album
    end
  end

  def edit
    @band = @album.band
  end

  def update
    if @album.update(album_params)
      redirect_to @album
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def show
  end

  def index
    @albums = Album.all
  end

  private

  def album_params
    params.require(:album).permit(:title, :album_type, :band_id)
  end

  def find_album
    @album = Album.find(params[:id])
  end

  def find_bands
    @bands = Band.all
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_album.html.erb
<li><%= link_to(album.title, album_url(album)) %></li>

app/views/albums/_form.html.erb
<%= form_helper(action, method) %>
  <label>Band:
    <select name="album[band_id]">
      <% bands.each do |b|%>
        <option value="<%= b.id %>" <%= "Selected" if b == band %>><%= b.name %></option>
      <% end %>
    </select>
  </label>
  <br>
  <label>Title: <input type="text" name="album[title]" value="<%= album.try(:title)%>"></label>
  <br>
  <label>Album type: </label>
  <input type="radio" name="album[album_type]" value="studio" <%= "checked" if album.try(:album_type) == "studio" %>>Studio
  <input type="radio" name="album[album_type]" value="live"<%= "checked" if album.try(:album_type) == "live" %>>Live
  <br>
  <input type="submit" value="<%= button_text %>">

</form>

app/views/albums/edit.html.erb
<h1>Edit Album</h1>


<%= render 'form', band: @band,
                   bands: @bands,
                   album: @album,
                   action: album_url(@album),
                   method: 'PATCH',
                   button_text: "Submit Changes" %>

app/views/albums/index.html.erb
<h1>All Albums</h1>
<ul>
  <%= render @albums %>
</ul>

<br>
<%= link_to("<< Back to Bands", bands_url) %>
<%= link_to("View All Tracks >>", tracks_url) %> 

app/views/albums/new.html.erb
<h1>Create a new album</h1>

<%= render 'form', band: @band,
                   bands: @bands,
                   album: @album,
                   action: albums_url,
                   method: 'POST',
                   button_text: "Create Album" %>
<%= link_to("<< Back to band", band_url(@band)) %>

app/views/albums/show.html.erb
<h1><%= @album.title %></h1>

<ul>
  <li>Artist: <%= @album.band.name %> </li>
  <li>Album type: <%=@album.album_type.capitalize  %></li>
</ul>

<h4>Track Listing</h4>
<ol>
  <%= render @album.tracks %>
</ol>


<%= button_to("Add Track", new_album_track_url(@album), method: :get) %>
<br>
<%= button_to("Edit Album", edit_album_url(@album), method: :get) %>
<br>
<%= button_to("Delete Album", album_url(@album), method: :delete) %>
<br>
<%= link_to("<< Back to band", band_url(@album.band)) %>