config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show] do
    get 'activate', on: :member
  end
  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    resources :albums, on: :member, only: [:new]
  end

  resources :albums, except: [:new] do
    resources :tracks, on: :member, only: [:new]
  end

  resources :tracks,  except: [:new] do
    resources :notes, on: :member, only: [:new, :create]
  end

  resources :notes, only: [:destroy, :update, :edit]
end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many :albums, dependent: :destroy
  has_many :tracks, through: :albums, source: :track
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :find_band, only: [:edit, :show, :destroy, :update]
  before_action :require_current_user!

  def new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to @band
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def destroy
    if @band.destroy
      redirect_to bands_url
    else
      flash.now[:errors] = ["Band is invincible"]
      render @band
    end
  end

  def edit
  end

  def update
    if @band.update(band_params)
      redirect_to @band
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def show
  end

  def index
    @bands = Band.all
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end

  def find_band
    @band = Band.find(params[:id])
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_band.html.erb
<li><%= link_to(band.name, band_url(band)) %></li>

app/views/bands/_form.html.erb
<%= form_helper(action, method) %>
  <label>Name: <input type="text" name="band[name]" value="<%= band.try(:name) %>"></label>
  <br> <br>
  <input type="submit" value="<%= button_text %>">
</form>

app/views/bands/edit.html.erb
<h1>Edit Band</h1>
<%= render "form", band: @band,
                   button_text: "Submit Changes",
                   action: band_url(@band),
                   method: "PATCH" %>
<br>
<%= link_to("<< Back to band", band_url(@band)) %>

app/views/bands/index.html.erb
<h1>All Bands</h1>

<ul>
  <%= render @bands %>
</ul>


<%= button_to("Add Band", new_band_url, method: :get) %>
<br>
<%= link_to("View all Albums >>", albums_url) %>

app/views/bands/new.html.erb
<h1>Create a new band</h1>
<%= render "form", band: @band,
                   button_text: "Create Band",
                   action: bands_url,
                   method: 'POST' %>
<br>
<%= link_to("<< Back to all bands", bands_url) %>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<h4>Albums</h4>
<ul>
  <%= render @band.albums %>
</ul>


<%= button_to("Add Album", new_band_album_url(@band), method: :get) %>
<br>
<%= button_to("Edit Band", edit_band_url(@band), method: :get) %>
<br>
<%= button_to("Delete Band", band_url(@band), method: :delete) %>
<br>
<%= link_to("<< Back to all bands", bands_url) %>